import { AiFillExperiment } from 'react-icons/ai';
import {
  BiSolidCoffeeAlt,
  BiSolidDryer,
  BiSolidHeart,
  BiSolidPlaneAlt,
  BiSolidTraffic,
  BiSolidTrain,
  BiSolidTree,
  BiWater,
} from 'react-icons/bi';
import {
  BsFillCloudRainFill,
  BsFillCloudRainHeavyFill,
  BsFillDropletFill,
  BsFillKeyboardFill,
  BsFire,
  BsPeopleFill,
  BsSoundwave,
  BsUmbrellaFill,
} from 'react-icons/bs';
import {
  FaCarSide,
  FaCat,
  FaChurch,
  FaCity,
  FaClock,
  FaCrow,
  FaDog,
  FaFan,
  FaFrog,
  FaHeadphonesAlt,
  FaHorseHead,
  FaKeyboard,
  FaLeaf,
  FaRegSnowflake,
  FaRoad,
  FaShoppingBasket,
  FaSubway,
  FaTree,
  FaWater,
  FaWind,
} from 'react-icons/fa';
import { FaBookOpen } from 'react-icons/fa6';
import {
  GiCarousel,
  GiChicken,
  GiCow,
  GiCricket,
  GiEgyptianBird,
  GiFilmProjector,
  GiOwl,
  GiSailboat,
  GiSeagull,
  GiSheep,
  GiSoundWaves,
  GiStonePile,
  GiSubmarine,
  GiTreeBeehive,
  GiVillage,
  GiWashingMachine,
  GiWaterfall,
  GiWhaleTail,
  GiWindchimes,
  GiWindow,
  GiWolfHead,
} from 'react-icons/gi';
import { HiOfficeBuilding } from 'react-icons/hi';
import { IoIosRadio } from 'react-icons/io';
import { IoMusicalNotes, IoRestaurant } from 'react-icons/io5';
import {
  MdConstruction,
  MdLocationPin,
  MdOutlineThunderstorm,
  MdRadio,
  MdSmartToy,
  MdTempleBuddhist,
  MdWaterDrop,
} from 'react-icons/md';
import {
  PiBirdFill,
  PiDogBold,
  PiRoadHorizonFill,
  PiSirenBold,
  PiTentFill,
  PiVinylRecord,
} from 'react-icons/pi';
import {
  RiBubbleChartFill,
  RiFilePaper2Fill,
  RiSparkling2Fill,
} from 'react-icons/ri';
import {
  TbBeerFilled,
  TbBowlFilled,
  TbSailboat,
  TbScubaMask,
  TbWaveSine,
  TbWaveSquare,
  TbWiper,
} from 'react-icons/tb';

import type { IconType } from 'react-icons';
import type { SoundIconId } from '@/data/icon-ids';

const ICONS: Record<SoundIconId, IconType> = {
  AiFillExperiment,
  BiSolidCoffeeAlt,
  BiSolidDryer,
  BiSolidHeart,
  BiSolidPlaneAlt,
  BiSolidTraffic,
  BiSolidTrain,
  BiSolidTree,
  BiWater,
  BsFillCloudRainFill,
  BsFillCloudRainHeavyFill,
  BsFillDropletFill,
  BsFillKeyboardFill,
  BsFire,
  BsPeopleFill,
  BsSoundwave,
  BsUmbrellaFill,
  FaBookOpen,
  FaCarSide,
  FaCat,
  FaChurch,
  FaCity,
  FaClock,
  FaCrow,
  FaDog,
  FaFan,
  FaFrog,
  FaHeadphonesAlt,
  FaHorseHead,
  FaKeyboard,
  FaLeaf,
  FaRegSnowflake,
  FaRoad,
  FaShoppingBasket,
  FaSubway,
  FaTree,
  FaWater,
  FaWind,
  GiCarousel,
  GiChicken,
  GiCow,
  GiCricket,
  GiEgyptianBird,
  GiFilmProjector,
  GiOwl,
  GiSailboat,
  GiSeagull,
  GiSheep,
  GiSoundWaves,
  GiStonePile,
  GiSubmarine,
  GiTreeBeehive,
  GiVillage,
  GiWashingMachine,
  GiWaterfall,
  GiWhaleTail,
  GiWindchimes,
  GiWindow,
  GiWolfHead,
  HiOfficeBuilding,
  IoIosRadio,
  IoMusicalNotes,
  IoRestaurant,
  MdConstruction,
  MdLocationPin,
  MdOutlineThunderstorm,
  MdRadio,
  MdSmartToy,
  MdTempleBuddhist,
  MdWaterDrop,
  PiBirdFill,
  PiDogBold,
  PiRoadHorizonFill,
  PiSirenBold,
  PiTentFill,
  PiVinylRecord,
  RiBubbleChartFill,
  RiFilePaper2Fill,
  RiSparkling2Fill,
  TbBeerFilled,
  TbBowlFilled,
  TbSailboat,
  TbScubaMask,
  TbWaveSine,
  TbWaveSquare,
  TbWiper,
};

interface SoundIconProps {
  id: SoundIconId;
}

export function SoundIcon({ id }: SoundIconProps) {
  const Icon = ICONS[id];

  return <Icon />;
}
